### PR TITLE
Update to blazor 3.2 preview 1 and netstandard21

### LINKED ISSUE #21: Remove workaround for System.Memory in test project
Can we remove the [workaround](https://github.com/csnewman/BlazorSignalR/blob/master/test/BlazorSignalR.Test.Client/BlazorSignalR.Test.Client.csproj#L21-L24) for the `System.Memory` assembly in the test project?  

I didn't test this during the upgrade to Asp.Net Core 3.0 preview 4.

### PR DESCRIPTION
**Pull request by Regenhardt**
Some packages are on 3.1.1 now.
Closes #21, #40, #41

Review please.

Had run problems so I basically re-created the test projects and copied the files in, after finding something about build target being defined on project creation preventing me from running the application. So that messed with the solution file.

Also, can I add an editorconfig file? Could lay out some ground rules like "use utf8" and ignore unused expression values.

### CODE REVIEW

**Comment by Regenhardt** [comment]
Also I removed the workaround to see the error, and it didn't show so I just kept it removed.

**Comment by csnewman** [comment]
Sure, adding an `editorconfig` is probably a decent idea

**Comment by Regenhardt** [comment]
Also makes https://github.com/csnewman/BlazorSignalR/pull/42 obsolete.

**Comment by Regenhardt** [comment]
Is the editorconfig ok like this, or should I put it in a seperate commit?

**Review by csnewman — CHANGES_REQUESTED** [review]
Can you bump the version number?

The identing seems to have been edited in places?

**Comment by csnewman** [comment]
Its fine in this PR

**Comment by Regenhardt** [comment]
Whoops, forgot to actually fixup the fixup-commit. 
Fixed the indenting and bumped the version.

**Review by csnewman — CHANGES_REQUESTED** [review]
Could you also update the readme with the version number?

**Comment by Regenhardt** [comment]
Right, I totally forgot that. I also updated the aspentcore version in the Readme.

**Comment by csnewman** [comment]
Thanks for this. I'll roll a NuGet package soon.

**Comment by dazinator** [comment]
Hold on a sec.. Is this strictly necessary - in blazor 3.2 preview 1  it seems microsoft signal r client is now working: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/

**Comment by Regenhardt** [comment]
It seems this should be obsolete now. Although I can't "just make it work" right now using this chat as a basis, not sure why. Maybe you can see what's wrong:
https://github.com/Regenhardt/BlazorSignalR/tree/feature/obsolescense

**Pull request merged**
