### PR TITLE
Update for preview9

### PR DESCRIPTION
**Pull request by LunicLynx**
# Update for preview9

* Updated depedencies
* `WebAssemblyUriHelper` replaced by using `NavigationManager`.
* Breaking changes corrected

### CODE REVIEW

**Comment by LunicLynx** [comment]
`WebAssemblyUriHelper` was removed replaced it by using `NavigationManager`.

**Comment by csnewman** [comment]
Overlaps with #35 going to need to take a look into the two PRs a bit more.

**Comment by dazinator** [comment]
I think this PR as it uses NavigationManager to get the base url - is preferrable to #35 (which uses JS interop.)

**Comment by tylerhartwig** [comment]
When will this be made available on nuget? Thanks for all the good work :D

**Comment by csnewman** [comment]
@tylerhartwig `0.10.0-blazor-3.0.0-preview9.19424.4` has been released on NuGet.

**Pull request merged**
